Repository haskell-unordered-containers/unordered-containers, pull requests merged in 2020-06, with the labels that each got.

#216 Fix complexity of intersectionWith and intersectionWithKey
  Data/HashMap/Base.hs
Labels: documentation

#209 Faster hashing for HashMaps
  Data/HashMap/Base.hs
  benchmarks/Benchmarks.hs
Labels: performance

#251 Add `instance Bifoldable HashMap`
  Data/HashMap/Base.hs
  tests/HashMapProperties.hs
Labels: feature-request

#231 Document that the Eq instances cannot guarantee substitutivity
  Data/HashMap/Base.hs
  Data/HashSet/Base.hs
Labels: documentation

#246 Add 'fromListWithKey' to HashMap
  Data/HashMap/Base.hs
  Data/HashMap/Lazy.hs
  Data/HashMap/Strict.hs
  Data/HashMap/Strict/Base.hs
  tests/HashMapProperties.hs
Labels: feature-request
